import { supabase } from './supabase-config.js';

const defaults={heroTitle:'관찰하고,\n더 나은 경험을\n만듭니다.',heroIntro:'디지털 제품과 브랜드에\n명료한 방향을 더하는 디자이너입니다.',aboutTitle:'생각의 빈틈을\n형태로 채웁니다.',aboutText:'서울을 기반으로 활동하며, 브랜드의 본질을 발견하고 사람들이 자연스럽게 머무는 경험을 설계합니다.',heroSize:'100',aboutSize:'62',heroBg:'#f2f0ea',contactBg:'#171714',email:'hello@example.com',projectTitle0:'Ovoid / Wellness',projectDetail0:'Brand identity · 2025',projectTitle1:'Juun / Editorial',projectDetail1:'Art direction · 2025',projectTitle2:'Objects in form',projectDetail2:'Digital experience · 2024'};
const login=document.querySelector('#login'),dashboard=document.querySelector('#dashboard'),notice=document.querySelector('#notice');let imageUrls={};
function updateRanges(){['heroSize','aboutSize'].forEach(key=>document.querySelector('#'+key+'Value').textContent=document.querySelector(`[name="${key}"]`).value+'px')}
async function loadContent(){const {data,error}=await supabase.from('site_content').select('content').eq('id','main').single();if(error)throw error;const content={...defaults,...data.content};Object.entries(defaults).forEach(([key])=>{const input=document.querySelector(`[name="${key}"]`);if(input)input.value=content[key]});imageUrls=Object.fromEntries(Object.entries(content).filter(([key])=>key.startsWith('projectImage')||key==='heroImage'));updateRanges()}
async function showDashboard(){login.hidden=true;dashboard.hidden=false;try{await loadContent()}catch(error){notice.textContent='데이터를 불러올 수 없습니다. 설정 SQL을 실행했는지 확인하세요.';console.error(error)}}
const {data:{session}}=await supabase.auth.getSession();if(session)showDashboard();
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='로그인 중…';const {error}=await supabase.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});button.disabled=false;button.textContent='로그인 →';if(error){alert('이메일 또는 비밀번호를 확인해 주세요.')}else showDashboard()});
document.querySelectorAll('.range').forEach(input=>input.addEventListener('input',updateRanges));
document.querySelectorAll('.image-input').forEach(input=>input.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){alert('3MB 이하의 이미지를 선택해 주세요.');e.target.value='';return}notice.textContent='이미지를 준비 중입니다…';const index=e.target.dataset.index;const path=`project-${index}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await supabase.storage.from('portfolio-images').upload(path,file,{upsert:false});if(error){notice.textContent='이미지 업로드에 실패했습니다.';return}const {data}=supabase.storage.from('portfolio-images').getPublicUrl(path);imageUrls['projectImage'+index]=data.publicUrl;notice.textContent='이미지가 업로드되었습니다. 저장 버튼을 눌러 반영하세요.'}));
document.querySelector('#heroImageInput')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){alert('3MB 이하의 이미지를 선택해 주세요.');e.target.value='';return}notice.textContent='메인 이미지를 업로드 중입니다…';const path=`hero/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await supabase.storage.from('portfolio-images').upload(path,file,{upsert:false});if(error){notice.textContent='이미지 업로드에 실패했습니다.';return}const {data}=supabase.storage.from('portfolio-images').getPublicUrl(path);imageUrls.heroImage=data.publicUrl;notice.textContent='메인 이미지가 업로드되었습니다. 변경사항 저장하기를 누르면 홈페이지에 반영됩니다.'});
document.querySelector('#removeHeroImage')?.addEventListener('click',()=>{delete imageUrls.heroImage;document.querySelector('#heroImageInput').value='';notice.textContent='변경사항 저장하기를 누르면 메인 이미지가 제거됩니다.'});
document.querySelectorAll('.remove-image').forEach(button=>button.addEventListener('click',()=>{delete imageUrls['projectImage'+button.dataset.index];document.querySelector(`.image-input[data-index="${button.dataset.index}"]`).value='';notice.textContent='저장 버튼을 누르면 기본 이미지로 돌아갑니다.'}));
document.querySelector('#settingsForm').addEventListener('submit',async e=>{try{const formData=Object.fromEntries(new FormData(e.currentTarget));localStorage.setItem('site_content_main',JSON.stringify({...formData,...imageUrls}))}catch(err){}e.preventDefault();notice.textContent='저장 중…';const content={...Object.fromEntries(new FormData(e.currentTarget)),...imageUrls};const {error}=await supabase.from('site_content').upsert({id:'main',content,updated_at:new Date().toISOString()});notice.textContent=error?'저장에 실패했습니다.':'저장되었습니다. 홈페이지를 새로고침해 확인하세요.'});
document.querySelector('#logout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});
